export const WIDTH_CHANGED      = 'WIDTH_CHANGED';
export const HEIGHT_CHANGED     = 'HEIGHT_CHANGED';
export const DENSITY_CHANGED    = 'DENSITY_CHANGED';
export const MAZEDIMS_CHANGED   = 'MAZEDIMS_CHANGED';